# Generated by Django 3.0.5 on 2020-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
