# Generated by Django 3.0.5 on 2020-04-26 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200426_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='date',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='time',
        ),
        migrations.AddField(
            model_name='clients',
            name='entry',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 14, 15, 26, 872610, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
    ]
